Deymoslor/Eventually_v2.1

- app/src/main/res/layout/activity_registro__usuarios.xml
Prueba realmente 3 pero bueno, 2. . .
> Prueba 2 trabajo conjunto.

- app/src/main/res/layout/activity_registro__usuarios.xml
Cambio al horizontal (cruce dedos)
> Pruba_016_07_Horizontal

- app/src/main/res/layout/activity_registro__usuarios.xml
colocandole id a los edit text para el registro y ademas arreglando un error en la gravedad de estos
> arreglando id y gravity del linear

- app/src/main/res/layout/activity_registro__usuarios.xml
Cambio a las mayusculas de los id de los botones y edtiext.
> Cambio mayusculas botonoes y editext

- app/src/main/res/layout/activity_registro__usuarios.xml
quite una propiedad del boton cancelar que no hacia nada
> cambio a la nada

- app/src/main/java/cursos/alain/eventually_v2/Adapters/AdapterGrupos.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentGrupos.java
- app/src/main/java/cursos/alain/eventually_v2/entidades/Grupos.java
- app/src/main/res/layout/grupos_fragment.xml
- app/src/main/res/layout/lista_grupos.xml
Agregando el recycler view con diferentes Cardview en el fragemnt Grupos.
> Agregando recyclerview

- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/activity_registros_admin.xml
Creación de todo el código para consultar los usuarios de el WS, modificación a id de registros_admin.
> Cambio a variables y creacion de consulta

- app/src/main/AndroidManifest.xml
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/activity_registros_admin.xml
Puesta a funcion de las consultas de los clientes desde la parte de el administrador.
> Consulta de Clientes

- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/activity_registro__usuarios.xml
Código de actualización y eliminación de  usuarios con el WS.
> Actualizar y eliminar usuarios.

- app/src/main/java/cursos/alain/eventually_v2/Drawer_principal.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/DetalleGrupoFragment.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentGrupos.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentIntereses.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentPersonalizarCuenta.java
- app/src/main/java/cursos/alain/eventually_v2/entidades/Grupos.java
- app/src/main/java/cursos/alain/eventually_v2/iComunicaFragments.java
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/detalle_grupo_fragment.xml
- app/src/main/res/layout/fragment_intereses.xml
- app/src/main/res/layout/fragment_personalizar_cuenta.xml
- app/src/main/res/menu/drawer_menu.xml
- app/src/main/res/values/strings.xml
Se le coloca el cardview los diferentes eventos y lo que lleva a otro fragment luego a el usuario se le agrege la parte de intereses y personalizar usuario osea lo que puede ser actualizar apodo o contra.
> Cardview y organizar usuario

- .idea/.name
- app/src/main/res/layout/fragment_inicio.xml
> color fondo

- app/src/main/res/layout/fragment_inicio.xml
Cmabie unas cositas que hacian que se dañara la aplicacion al entrar en el fragmento inicio.
> InicioFragment

- app/src/main/res/layout/fragment_inicio.xml
Cambie el color del fondo en el archivo fragment inicio XD
> Cambio color fondo

- app/src/main/res/layout/fragment_inicio.xml
Arreglando el daño que hizo navia en el fondo de el fragmento inicio.
> arreglo en el fondo

- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/content_main.xml
Cambio en el MainActivity java y xml, que permite la validación de usuarios incorporados en la BD.
> Login funcional

- app/build.gradle
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentGrupos.java
- app/src/main/res/drawable/ic_creargrupo.xml
- app/src/main/res/layout/grupos_fragment.xml
Creando el fab en la atividad de mis grupos para proximamente agregar la funcionalidad de crear tus propios grupos en la app.
> FAB grupos

- app/src/main/AndroidManifest.xml
- app/src/main/java/cursos/alain/eventually_v2/Drawer_principal.java
- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/Presentacion.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/activity_presentacion.xml
- app/src/main/res/layout/activity_registros_admin.xml
- app/src/main/res/values/strings.xml
Preferencia y activity que permite directamente loggear sin necesidad de poner datos y darle a iniciar sesión, también botón de cerrar sesion.
> Preferencias.

- app/src/main/res/layout/fragment_inicio.xml
- app/src/main/res/layout/fragment_personalizar_cuenta.xml
- app/src/main/res/menu/drawer_menu.xml
- app/src/main/res/values/strings.xml
Creando los espacios para la personalizacion de la informacion del cliente como usuario y la foto.
> Usuario registros

- app/src/main/AndroidManifest.xml
- app/src/main/java/cursos/alain/eventually_v2/Drawer_principal.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentPermisoPersonalizarCuenta.java
- app/src/main/java/cursos/alain/eventually_v2/PersonalizarDatosUsuario.java
- app/src/main/java/cursos/alain/eventually_v2/ValidacionPersonalizaCuente.java
- app/src/main/res/layout/activity_personalizar_datos_usuario.xml
- app/src/main/res/layout/activity_validacion_personaliza_cuente.xml
- app/src/main/res/layout/fragment_permiso_personalizar_cuenta.xml
- app/src/main/res/values/strings.xml
Jordi y yo creamos el front end para la personalizacion de la cuenta
> Cambios navia

- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/res/layout/activity_validacion_personaliza_cuente.xml
> Arreglando lo de navia

- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/ValidacionPersonalizaCuente.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/activity_validacion_personaliza_cuente.xml
Prueba crash de la app al entrar en el drawer para probar editar usuarios
> Prueba_Usuarios_Edit

- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/PersonalizarDatosUsuario.java
- app/src/main/java/cursos/alain/eventually_v2/ValidacionPersonalizaCuente.java
- app/src/main/res/layout/activity_personalizar_datos_usuario.xml
> Arreglando para registros de usaurios

- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/ValidacionPersonalizaCuente.java
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/activity_registro__usuarios.xml
- app/src/main/res/layout/activity_registros_admin.xml
- app/src/main/res/values/strings.xml
unchingo de cambios en el backend pero vamos que se mejora todo!
> rebuild del back end

- app/src/main/AndroidManifest.xml
- app/src/main/java/cursos/alain/eventually_v2/CreacionGrupo.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentGrupos.java
- app/src/main/res/layout/activity_creacion_grupo.xml
- app/src/main/res/values/strings.xml
Cree el front end necesario para poder realizar el registro de los grupos que pueden crear los usuarios.
> Front en para la crear grupos

- app/src/main/java/cursos/alain/eventually_v2/CreacionGrupo.java
- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/Presentacion.java
- app/src/main/res/layout/activity_creacion_grupo.xml
Ya funciona el envio de datos a la hora de crear los grupos mediante el nuevo activity de creación de grupos.
> Back de creación de grupo.

- app/src/main/java/cursos/alain/eventually_v2/CreacionGrupo.java
- app/src/main/java/cursos/alain/eventually_v2/Drawer_principal.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentGrupos.java
- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/PersonalizarDatosUsuario.java
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
Ahora cuando se crea un registro en la trabla grupo, la persona tambien generara un registro en la tabla Usuario_Grupo, de modo que se tendra conocimiento de quien creo el grupo.
> Conexion con la tabla usuario grupo

- app/src/main/java/cursos/alain/eventually_v2/Drawer_principal.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/InicioFragment.java
- app/src/main/java/cursos/alain/eventually_v2/interfaces/iComunicaFragments.java
- app/src/main/res/layout/fragment_inicio.xml
Metiendo un onclick en las cardviews por medio de un video de strooopers :D
> Onclick en las CardViews

- app/src/main/java/cursos/alain/eventually_v2/CreacionGrupo.java
- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/PersonalizarDatosUsuario.java
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/res/layout/activity_personalizar_datos_usuario.xml
Cambios realizados a la adición de usuario luego de entrar a la app, ya no hay etiquetas ni fecha, pero se adiciona fecha de nacimiento.
> Cambios a la adición de usuario

- app/src/main/java/cursos/alain/eventually_v2/Drawer_principal.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentBuscarGrupos.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/InicioFragment.java
- app/src/main/java/cursos/alain/eventually_v2/interfaces/iComunicaFragments.java
- app/src/main/res/layout/fragment_buscar_grupos.xml
- app/src/main/res/layout/fragment_inicio.xml
- app/src/main/res/layout/lista_buscargrupos.xml
- app/src/main/res/menu/drawer_menu.xml
- app/src/main/res/values/strings.xml
Organize los eventos y los fragments necesario para mostrar las eqtiquetas proximamente en la app.
> Buscar grupos(Preparado para jordan)

- app/src/main/java/cursos/alain/eventually_v2/Adapters/BuscarGruposAdapter.java
- app/src/main/java/cursos/alain/eventually_v2/CreacionGrupo.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentBuscarGrupos.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/MisGruposFragment.java
- app/src/main/java/cursos/alain/eventually_v2/entidades/Buscar_Grupos.java
- app/src/main/java/cursos/alain/eventually_v2/entidades/Grupos1.java
- app/src/main/res/layout/lista_buscargrupos.xml
Implementación de todo el código necesario para poder consultar por etiquetas y luego ser adaptado a filtración.
> Busqueda por etiqueta:

- app/src/main/java/cursos/alain/eventually_v2/Adapters/BuscarGruposAdapter.java
- app/src/main/java/cursos/alain/eventually_v2/CreacionGrupo.java
- app/src/main/java/cursos/alain/eventually_v2/Drawer_principal.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/DetalleBuscarGrupoFragment.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/FragmentBuscarGrupos.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/MisGruposFragment.java
- app/src/main/java/cursos/alain/eventually_v2/MainActivity.java
- app/src/main/java/cursos/alain/eventually_v2/PersonalizarDatosUsuario.java
- app/src/main/java/cursos/alain/eventually_v2/entidades/Buscar_Grupos.java
- app/src/main/java/cursos/alain/eventually_v2/interfaces/iComunicaFragments.java
- app/src/main/java/cursos/alain/eventually_v2/registro_Usuarios.java
- app/src/main/java/cursos/alain/eventually_v2/registros_admin.java
- app/src/main/res/layout/fragment_buscar_grupos.xml
- app/src/main/res/layout/fragment_detalle_buscar_grupo.xml
- app/src/main/res/layout/fragment_mis_grupos.xml
- app/src/main/res/layout/lista_buscargrupos.xml
> PAPA COMMIT

- app/src/main/AndroidManifest.xml
- app/src/main/java/cursos/alain/eventually_v2/Adapters/BuscarGruposDetalleAdapter.java
- app/src/main/java/cursos/alain/eventually_v2/Adapters/GruposAdapter.java
- app/src/main/java/cursos/alain/eventually_v2/Drawer_principal.java
- app/src/main/java/cursos/alain/eventually_v2/EventoActivity.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/DetalleBuscarGrupoFragment.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/DetalleGruposBuscarGruposFragment.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/DetalleMisGrupos.java
- app/src/main/java/cursos/alain/eventually_v2/Fragments/MisGruposFragment.java
- app/src/main/java/cursos/alain/eventually_v2/PersonalizarDatosUsuario.java
- app/src/main/java/cursos/alain/eventually_v2/VerEventoActivity.java
- app/src/main/java/cursos/alain/eventually_v2/entidades/Grupos1.java
- app/src/main/java/cursos/alain/eventually_v2/interfaces/iComunicaFragments.java
- app/src/main/res/drawable/ic_baseline_exit_to_app_24.xml
- app/src/main/res/layout/activity_evento.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_ver_evento.xml
- app/src/main/res/layout/fragment_detalle_buscar_grupo.xml
- app/src/main/res/layout/fragment_detalle_grupos_buscar_grupos.xml
- app/src/main/res/layout/fragment_detalle_mis_grupos.xml
- app/src/main/res/layout/fragment_inicio.xml
- app/src/main/res/layout/lista_grupos.xml
- app/src/main/res/layout/lista_grupos_detalle.xml
- app/src/main/res/menu/drawer_menu.xml
- app/src/main/res/values/strings.xml
Este es el ultimo commit de la app agradecimientos a mi <3
> El mismisimo ultimo commit
